### ISSUE TITLE
Vanced doesn't start when Google Account Linked

### ISSUE THREAD

**Issue by TheCybertronic** [YTVanced/VancedMicroG#102]
When being logged in with my Google Account in MicroG, YouTubeVanced doesn't load any content. When removing the account everything seems fine.

Tested this behavior on 2 different devices.

Edit: Doesn't load means that not even the feed is being loaded - neither do the navigation links at the bottom work.

**Comment by gghhkm** [comment]
1. Install Vanced ***15.40.37*** or lower via the manager
2. Login
3. Update to latest
