### ISSUE TITLE
Can't signin Google account

### ISSUE THREAD

**Issue by rattanakchea** [YTVanced/VancedMicroG#103]
Signed bin account not show up in YouTube vanced. When try to sign in again, it says account already log in.

The issue appear after updating my Samsung 21 to latest version, 
https://doc.samsungmobile.com/SM-G998U1/XAA/doc.html.

**Comment by gghhkm** [comment]
This has been answered many many many times already.
[Vanced Discord Invite](https://discord.gg/h9YzVJCRBF)
[Discord Pinned Message](https://discord.com/channels/328493314485518336/358967876193091584/809525073903616022)

**Comment by rattanakchea** [comment]
@gghhkm where do I find the response? Obviously I am not supposed to know
