### ISSUE TITLE
Problem singing in YT Vanced/Micro G

### ISSUE THREAD

**Issue by GeorgeRB224** [YTVanced/VancedMicroG#104]
YToday when I open the app, the error was, you're disconnected, please check your internet connection, but I was well connect to my Wifi. So I  reinstall the app, but now I can't sing in with my account, when I try to, the app didn't add my account and it star charging infinitely. Please help, I did everything that said the Vanced guide, but it didn't work

**Comment by gghhkm** [comment]
![106367604-d2f81680-6311-11eb-8aa3-ca34f964d7a7](https://user-images.githubusercontent.com/72711094/111645775-71174180-87d7-11eb-976f-09f77f2ff606.jpg)
[Vanced Discord](Https://discord.gg/Vanced)
