### ISSUE TITLE
Installation's issues

### ISSUE THREAD

**Issue by KiraineM** [YTVanced/VancedMicroG#105]
I don't understand anything in code, but check all your FAQ, and can't fix my problem.
I already have YouTube Vanced almost 2 years, ver. 14. Today I closed all sessions in Google Account and after it can't enter in my account in YTVanced. I checked all permissions from it in settings, tried to figure isn't app unlog from my Google account. Cleaned all cash, and reset to standard settings. But it's not helped. I deleted micro g and Vanced, downloaded Vanced manager from official website, but have troubles with instal on phone. Can't give roots rights to this app, cause phone give error. In ending of installation micro g in manager, check this error INSTALL_FAILED_INTERNAL_ERROR: permission denied. But I don't do anything, when it's installing. 
![Screenshot_2021-03-11-15-30-56-483_com vanced manager](https://user-images.githubusercontent.com/80466874/110798992-5dbe2080-8283-11eb-8c09-8da6dbfa50c2.png)

**Comment by gghhkm** [comment]
Disable MiUi optimization.

**Comment by KiraineM** [comment]
All works! Thank you so much!
