### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by COLEplusTEN** [YTVanced/VancedMicroG#106]
I go through the process of signing in. I verify the login and I just end up back at the sign in and I'm not signed in. I'm running Android 12.

**Comment by Rehansikdar** [comment]
Same here

**Comment by Arko0321** [comment]
Same here

**Comment by BreakfastSerial** [comment]
I have a a similar issue. I can login, but face the Vanced microG Settings again.
If I try to add the account again, I receive the message that the account is already registered on the device.

Youtube Vanced on the other hand won't load anything anymore (black screen), after I failed to sign in.
Reinstalls or reboots change nothing.


**BUT**, if you read the messages from Vanced Manager, when installing microG/Youtube Vanced, you'll notice:

 - Install Youtube Vanced 15.43.32
 - Open Youtube Vanced and log in
 - Update Youtube Vanced

It clearly states, this is currently a known bug and they provide a workaround.

**Comment by gghhkm** [comment]
![106367604-d2f81680-6311-11eb-8aa3-ca34f964d7a7](https://user-images.githubusercontent.com/72711094/111645775-71174180-87d7-11eb-976f-09f77f2ff606.jpg)
