### ISSUE TITLE
Signing in issue

### ISSUE THREAD

**Issue by samcode44** [YTVanced/VancedMicroG#117]
Signing in Bug on latest MicroG and youtube vanced for google account didn't fixed till now, please vanced team fix this bug and thanks in advance.

**Comment by madunist** [comment]
I've downgraded previous versions of them. ( Vanced 15.43.32, MicroG 0.2.16.204713) It's working fine.

**Comment by KevinX8** [comment]
it's only related to the vanced version not microg.

**Comment by samcode44** [comment]
Thanks for replying, i've also downgraded my installed ones and thats
working fine.

**Comment by samcode44** [comment]
thanks for your reply, Now thats working fine....

**Comment by krishankit3820** [comment]
Same issue for me but let me know once you fix this issue.
