### ISSUE TITLE
[bug] microG says im offline, have to reinstall for fix

### ISSUE THREAD

**Issue by GGamer2042** [YTVanced/VancedMicroG#120]
MicroG sometimes says im offline in yt vanced (its not vanced fault because clearing vanceds data doesnt fix it, only fixes after reinstallation of microg), also there is this bug when it only displays my base account and not my channels of that account in the accounts menu (duh)

**Comment by X1nto** [comment]
Follow Vanced FAQ to fix that issue

**Comment by GGamer2042** [comment]
Hey are you georgian?

**Comment by X1nto** [comment]
> Hey are you georgian?

Yep

**Comment by GGamer2042** [comment]
Cool me too

**Comment by X1nto** [comment]
> Cool me too

Nice
