### ISSUE TITLE
MIUI 12 resets battery optimization after reboot with version 0.2.18 because of the icon hider I assume

### ISSUE THREAD

**Issue by luuk89** [YTVanced/VancedMicroG#121]
I had to switch to v.0.2.16 on my new Redmi10Note Pro running the latest MIUI 12 Global EU ROM. With version 0.2.18 I was not able to lock the app. When you don't lock it it resets the battery optimization settings back to default when I reboot the device. I think MIUI ROM also needs to be excluded from the icon hider...

https://imgbox.com/EuCZeN1E

**Comment by X1nto** [comment]
Blame MIUI, there's nothing we can do

**Comment by luuk89** [comment]
> 
> 
> Blame MIUI, there's nothing we can do

You can exclude MIUI from your icon hider right? Like you do with the HUAWEI ROM, I read this in the changelog for 2.18 at least. It is because in 2.18 the icon is hidden, I cannot lock it, therefore it resets. In 2.16 I have an Icon and I can lock it, and battery saver settings are retained.

**Comment by gghhkm** [comment]
> > Blame MIUI, there's nothing we can do
> 
> You can exclude MIUI from your icon hider right? Like you do with the HUAWEI ROM, I read this in the changelog for 2.18 at least. It is because in 2.18 the icon is hidden, I cannot lock it, therefore it resets. In 2.16 I have an Icon and I can lock it, and battery saver settings are retained.

You can switch off icon hiding in MicroG settings.

**Comment by X1nto** [comment]
> > Blame MIUI, there's nothing we can do
> 
> You can exclude MIUI from your icon hider right? Like you do with the HUAWEI ROM, I read this in the changelog for 2.18 at least. It is because in 2.18 the icon is hidden, I cannot lock it, therefore it resets. In 2.16 I have an Icon and I can lock it, and battery saver settings are retained.

As @gghhkm said, just turn off the switch in microG. Go to Vanced Manager and click settings in the microG item, then turn off the switch

**Comment by luuk89** [comment]
> 
> 
> > > Blame MIUI, there's nothing we can do
> > 
> > 
> > You can exclude MIUI from your icon hider right? Like you do with the HUAWEI ROM, I read this in the changelog for 2.18 at least. It is because in 2.18 the icon is hidden, I cannot lock it, therefore it resets. In 2.16 I have an Icon and I can lock it, and battery saver settings are retained.
> 
> As @gghhkm said, just turn off the switch in microG. Go to Vanced Manager and click settings in the microG item, then turn off the switch

Ah now I see. I didn't see you could enter the app via vanced manager. When IconHider is disabled MIUI retains its battery settings, cheers
