### ISSUE TITLE
Battery optimization microG

### ISSUE THREAD

**Issue by Ddemared** [YTVanced/VancedMicroG#132]
Hello, I have a problem with a microG message. The message says that you need to disable the battery optimization and then restart your phone. I disabeld the optimization and restarted my phone but the message doesn't go away. Could you fix that? I thank you for your time. 
-Daniël
![IMG_20210504_201642](https://user-images.githubusercontent.com/83667392/117050470-a939fb80-ad15-11eb-84d4-036bab98cb44.jpg)

**Comment by gghhkm** [comment]
https://dontkillmyapp.com 
You can disable the notification whenever.

**Comment by Ddemared** [comment]
Thnx got it
