### ISSUE TITLE
Random background crashes

### ISSUE THREAD

**Issue by CodeRunner42** [YTVanced/VancedMicroG#136]
MicroG randomly crashing in the background, all battery optimizations are turned off and with it crashing it also sometimes takes down the vanced app running or just seizes the phone itself. 

Crash logs
https://del.dog/inarfywoko

**Comment by milindgoel15** [comment]
Are u still facing such issue?

**Comment by CodeRunner42** [comment]
Seems it's fine so far think I'll close this
