### ISSUE TITLE
Impossible to cast video

### ISSUE THREAD

**Issue by Dave90o** [YTVanced/VancedMicroG#143]
Every time I try to cast video to tv, Yt Vanced show me a popup where it suggest to update Google play services. ( Also if there are update too ).impossible to cast :(. Please help me 🆘
Yt Vanced version 16.16.38
Micro google services 0.2.18.210500
Google play serivices 21.18.16

**Comment by JDMorris81** [comment]
Same issue with the latest Vance release. They just closed my issue, no telling when if ever they'll get around to actually addressing it.

**Comment by Oizaro** [comment]
> no telling when

We aren't able to fix that, so when the original author of MicroG will fix it, that could happens tomorrow or NEVER.
