### ISSUE TITLE
AOD  can't turn off

### ISSUE THREAD

**Issue by anantawakatta** [YTVanced/VancedMicroG#144]
Device:Redmi note 10
Micro g version : 0.2.18.210500
Miui:12.0.2.0
AOD system in Redmi note 10 will turn off after 10 seconds, but after I installed micro g, AOD keeps turning on and can't turn off

**Comment by milindgoel15** [comment]
MIUI related issue. Try using the latest vanced microG if you aren't already and see if it helps. Otherwise miui issue or upstream microG
