### ISSUE TITLE
Google servers error

### ISSUE THREAD

**Issue by SnowzinHue** [YTVanced/VancedMicroG#148]
my account whenever I try to log into the micro g, I get that error "there was a problem communicating with google servers"

I already tried with another account and it worked but this one I couldn't log in.

**Comment by AlphaPancake** [comment]
I've got the same issue. Also I use blockada 5 and since a day or so yt vanced can't even load any content.

**Comment by jacky96623** [comment]
@AlphaPancake I also encountered this issue. May I confirm that your solution is to install an older version of microG?

**Comment by milindgoel15** [comment]
For any issues related to offline issues, refer to this issue:  https://github.com/YTVanced/Vanced/issues/786
