### ISSUE TITLE
Micro g battery optimization

### ISSUE THREAD

**Issue by GabiGG0** [YTVanced/VancedMicroG#150]
I cannot turn off micro g battery optimization
![Screenshot_20210629_220249](https://user-images.githubusercontent.com/86253153/123853261-ec83a580-d925-11eb-8318-4b545095e2b5.jpg)

**Comment by Oizaro** [comment]
MicroG settings --> set "hide microg icon on launcher" to false

Now you should be able to see microg on that list.
