### ISSUE TITLE
Installation error on phone with microG

### ISSUE THREAD

**Issue by abougouffa** [YTVanced/VancedMicroG#153]
Hello,

I tried to install the last version  of VancedMicroG, the package does not install and I'm getting this error:

![IMG_20210705_170803.jpg](https://user-images.githubusercontent.com/3716399/124500926-eb88c300-ddc0-11eb-96d7-14f3ca564ef8.jpg)

I have to mention that I'm using a LineageOS phone with microG.

**Comment by Oizaro** [comment]
> Hello,
> 
> I tried to install the last version of VancedMicroG, the package does not install and I'm getting this error:
> 
> ![IMG_20210705_170803.jpg](https://user-images.githubusercontent.com/3716399/124500926-eb88c300-ddc0-11eb-96d7-14f3ca564ef8.jpg)
> 
> I have to mention that I'm using a LineageOS phone with microG.

Try this test package (uninstall previous first).

[Test.zip](https://github.com/YTVanced/VancedMicroG/files/6765891/Test.zip)

If works, I'll push another update.

**Comment by KevinX8** [comment]
Please avoid using the nonroot version if you have root already especially if you're using microg already unless you have some issue with the root version.

**Comment by abougouffa** [comment]
Thank you for your quick reply, it installed successfully.

I don't have a rooted phone, so the only option is to use the non root version.

Thanks again

**Comment by Oizaro** [comment]
> Thank you for your quick reply, it installed successfully.
> 
> I don't have a rooted phone, so the only option is to use the non root version.
> 
> Thanks again

Ensure that everything it works properly.

**Comment by Oizaro** [comment]
> Please avoid using the nonroot version if you have root already especially if you're using microg already unless you have some issue with the root version.

Eventually we could merge this changes. It's just a changed provider name (that shouldn't give any problem).

**Comment by abougouffa** [comment]
@Oizaro @KevinX8 

I confirm, it works fine, no particular problem.

Thank you for your responsiveness

**Comment by Oizaro** [comment]
https://github.com/YTVanced/VancedMicroG/pull/154

**Comment by abougouffa** [comment]
Hello @KevinX8  

Even though the #154 PR has been merged, there's still no 0.2.21.212417 **apk** on the [releases](https://github.com/YTVanced/VancedMicroG/releases) page!

**Comment by Oizaro** [comment]
@KevinX8 👆👆👆

**Comment by abougouffa** [comment]
Thank you @KevinX8 🙏🏼
