### ISSUE TITLE
MicroG update so it can work with Google chromecast

### ISSUE THREAD

**Issue by ThEnchanted** [YTVanced/VancedMicroG#156]
Could you update MicroG so it can work with Google chromecast?
(Google) now they added ads on it
Phone where it was tested: Samsung m21, Lg G7+ ThinQ and Lg G6
Android: 10, 8

**Comment by Oizaro** [comment]
> Could you update MicroG so it can work with Google chromecast?
> (Google) now they added ads on it
> Phone where it was tested: Samsung m21, Lg G7+ ThinQ and Lg G6
> Android: 10, 8

We can't fix this bug, unless the author of MicroG doesn't fix it himself.

We already pointed out this statement more than 1.000.000 time.
