### ISSUE TITLE
Please check network connection on OnePlus 9

### ISSUE THREAD

**Issue by NO111ONE** [YTVanced/VancedMicroG#168]
Unable to sign in to Vanced microG after adding account - YouTube vanced asks to check network connection. Tried full reinstall of Vanced. 
Using OnePlus 9 (LE2110) on ColorOS 11.2: 11.2.A.03 and 11.2.A.13
![IMG_20220101_215630](https://user-images.githubusercontent.com/63470411/147858576-1cf3dd23-ca7d-4daf-b7f8-729a92e22c4d.jpg)

**Comment by Gratenes** [comment]
Having the exact same problem - Samsung Galaxy Note s9

**Comment by hcker2000** [comment]
I to had this problem. Seems to happen when you are trying to use a google business account on a custom domain (myemail@mydomain.com)

**Comment by NO111ONE** [comment]
> I to had this problem. Seems to happen when you are trying to use a google business account on a custom domain ([myemail@mydomain.com](mailto:myemail@mydomain.com))

Probably it's the problem. I have a custom domain workspace account. It's also my main google account. Love the amount of restrictions I get just because I have an enterprise account.
