### ISSUE TITLE
Where can download YouTube vanced and YouTube music apk

### ISSUE THREAD

**Issue by YTiceice** [YTVanced/VancedMicroG#169]
I use miui 12,I want to use adb install APK
I need the shrimp link containing zh_tw.apk
And will continue to update the latest version of the link

**Comment by TheAmazingBen100** [comment]
And what's the problem with simply using the [vanced manager](https://vancedapp.com)?

**Comment by YTiceice** [comment]
But I use miui,so I need apk

**Comment by TheAmazingBen100** [comment]
No, you're using the manager. The manager works fine on miui, so long as you disable miui optimizations.

**Comment by KevinX8** [comment]
https://mirror.codebucket.de/vanced you can find a mirror of all apk files here

**Comment by YTiceice** [comment]
I don't want disable miui optimizations.

**Comment by TheAmazingBen100** [comment]
I think split apk installers also require you to disable miui optimizations, so you're disabling them either way round.

**Comment by YTiceice** [comment]
I just want apk files

**Comment by YTiceice** [comment]
Sorry

**Comment by TheAmazingBen100** [comment]
> https://mirror.codebucket.de/vanced you can find a mirror of all apk files here

If you absolutely need the apk files, here you go.
The vanced manager is still the easiest install method.

**Comment by YTiceice** [comment]
![Uploading Screenshot_2022-01-08-16-36-32-202_com.android.chrome.jpg…]()
Where

**Comment by YTiceice** [comment]
Oh I see

**Comment by YTiceice** [comment]
Thanks you
