### ISSUE TITLE
MicroG installation failed (Parse Error)

### ISSUE THREAD

**Issue by fahimrahmanbooom** [YTVanced/VancedMicroG#180]
MicroG shows parse error when installing from the latest version of vanced manager. 
Android Version: 5.1.1
Device: Fire HD 8 (7th Gen) Non Root

**Comment by IAMNOTRANA** [comment]
I'm having same issue. I asked around on their discord page and they said they drop android 5 completely.
![image](https://cdn.discordapp.com/attachments/882355463591698473/943957742740185118/1.png)

RIP us.

**Comment by fahimrahmanbooom** [comment]
Oh, that is so sad. BTW, thanks for letting me know.
[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
02/18/22,
01:53:16 AM

**Comment by alogblog** [comment]
[Vanced MicroG v0.2.22.212658](https://github.com/YTVanced/VancedMicroG/releases/tag/v0.2.22.212658-212658001)

I installed old(previous) version, and it worked.

**Comment by fahimrahmanbooom** [comment]
> [Vanced MicroG v0.2.22.212658](https://github.com/YTVanced/VancedMicroG/releases/tag/v0.2.22.212658-212658001)
> 
> I installed old(previous) version, and it worked.

Could you please share the version number? I have tried multiple but none of them worked. 
Thanks In Advance.

**Comment by IAMNOTRANA** [comment]
> 

https://www.apkmirror.com/apk/team-vanced/microg-youtube-vanced/
microG 0.2.21.212417 worked for me. 

As for Vanced
https://www.apkmirror.com/apk/team-vanced/youtube-vanced/
Vanced 16.29.39

**Comment by alogblog** [comment]
My device is Fire HD 10(7th generation)

Vanced Manager: 2.6.2(Crimson)
Youtube Vanced: 16.02.35
MicroG: 0.2.22.212658
(with No root option)

**Comment by fahimrahmanbooom** [comment]
> 

Thanks. It worked.
