### ISSUE TITLE
MicroG Not Responding

### ISSUE THREAD

**Issue by ghost** [YTVanced/VancedMicroG#185]
I'll be watching a video in Youtube Vanced, and all of a sudden I get the message "MicroG has stopped working" or something along those lines

Whether I choose "wait" or "close" the outcome does not change, it continues to show the message over and over 

I have to reset it somehow such as closing YouTube Vanced, restarting my phone, or clearing YouTube Vanced's cache which I feel may be related, Vanced gets to 500+ mbs of unnecessary cache for me

The biggest issue is that when this happens my phone will sometimes completely freeze and lock up, I was watching a video but decided to take a picture of something right quick, I went to camera, took the picture annnd my entire phone was locked, the camera still the showed the preview normally but I could do nothing, after about 1-2 minutes (A VERY LONG TIME) The phone will unfreeze and perform every action I pressed while frozen

I don't know if this is an issue between MicroG, Vanced, or both but it's annoying when it happens

**Comment by JapanYoshi** [comment]
Make sure battery optimization is disabled for MicroG in the settings.
![Screenshot_20220312_170949](https://user-images.githubusercontent.com/8707990/158009854-16fff391-4df6-4968-be84-4f703e33726a.png)
![Screenshot_20220312_171027](https://user-images.githubusercontent.com/8707990/158009861-c558fffc-f341-4f12-846b-83e884686dda.png)

**Comment by ghost** [comment]
Yeah for some reason battery optimization was on again, I turned it back off, suppose I'll close this issue
