### ISSUE TITLE
[Feature request] make MicroG work as a wrapper for all GMS

### ISSUE THREAD

**Issue by tschertel** [YTVanced/VancedMicroG#38]
Would it be possible?
Now, with Huawei phones coming without GMS, would be nice to have a wrapper for Google authentication, just like Youtube Vanced.
I have a P40 Pro Plus with GMaps, GBoard and G Translator, but I cannot make login.

**Comment by X1nto** [comment]
Uhh what? Vanced microg is literally a fork of what you want
