### ISSUE TITLE
Can't signin in huawei devices.

### ISSUE THREAD

**Issue by kentify** [YTVanced/VancedMicroG#44]
I've encountered it since sept. 11th.. I couldn't login my account even if i install or reinstall the vanced app.. any fix for this? 
my devices is Huawei Nova 7i... no GMS supported

**Comment by Oizaro** [comment]
In Vanced case, microG works like a bridge to official Play Services. Huawei devices doesn't have it anymore, so you can't login until a microG fix doesn't appear.

**Comment by Oizaro** [comment]
You can try to uninstall and reinstall latest microG version 0.2.11.

**Comment by kentify** [comment]
> You can try to uninstall and reinstall latest microG version 0.2.11.

already did. it was working last month but now it seems to be patched or been fix by google.. can I ask when will be the next update?

**Comment by Oizaro** [comment]
> > You can try to uninstall and reinstall latest microG version 0.2.11.
> 
> already did. it was working last month but now it seems to be patched or been fix by google.. can I ask when will be the next update?

It's not matter of when next update will be available, but if this will fix Google stuff on Huawei. Now there isn't a fix for that.

**Comment by Oizaro** [comment]
@kentify 

Login issue fix for Huawei/Honor or Any other device users
Solution: 

Workaround 1: (Credit: Leszek1337 from reddit)

1. First install the old microG version (remove the current one installed but keep the apk for it - you need it later). 

microg_YouTube_Vanced_0.2.4-105_16052019_2.apk (get from the old files link on vanced.app site)

2. Then open YouTube Vanced and try loging in again until it shows the error message. Try to at least ones reload it by tapping the error message. 

3. Now install the newer microG version again and restart vanced. It should be logged in again and everything should work again.

NOTE: Now make sure u disable battery optimization for both microg and vanced using dontkillmyapp.com otherwise your device software might kill microg and you might have to repeat all above steps again to fix login.


Workaround 2: (this is most likely to work so try this first)

1. Remove microg then reinstall it.

2. Then open microg app settings (use either activity launcher or open from vanced app settings) and turn off google cloud messaging and google device registration.

3. Add your account and enjoy

**Comment by kentify** [comment]
> @kentify
> 
> Login issue fix for Huawei/Honor or Any other device users
> Solution:
> 
> Workaround 1: (Credit: Leszek1337 from reddit)
> 
> 1. First install the old microG version (remove the current one installed but keep the apk for it - you need it later).
> 
> microg_YouTube_Vanced_0.2.4-105_16052019_2.apk (get from the old files link on vanced.app site)
> 
> 1. Then open YouTube Vanced and try loging in again until it shows the error message. Try to at least ones reload it by tapping the error message.
> 2. Now install the newer microG version again and restart vanced. It should be logged in again and everything should work again.
> 
> NOTE: Now make sure u disable battery optimization for both microg and vanced using dontkillmyapp.com otherwise your device software might kill microg and you might have to repeat all above steps again to fix login.
> 
> Workaround 2: (this is most likely to work so try this first)
> 
> 1. Remove microg then reinstall it.
> 2. Then open microg app settings (use either activity launcher or open from vanced app settings) and turn off google cloud messaging and google device registration.
> 3. Add your account and enjoy

for the first solusyon.. i downloaded the file you have suggested but .. when i open youtube vanced app (latest version) it just automatically close... my microg version is correct tho.. should i download also the older version one?

for second solusyon.. I already did this but.. its still has some error.. cannot connect to google server or something after i signin my gmail account

**Comment by Oizaro** [comment]
If you have correctly followed both workarounds and login still not work, you can't do anything else for now.

**Comment by kentify** [comment]
> If you have correctly followed both workarounds and login still not work, you can't do anything else for now.

Okay. Thanks for the recommendation.. I will be waiting for the next update

**Comment by Oizaro** [comment]
@kentify Fixed! ;)

**Comment by kentify** [comment]
> @kentify Fixed on last new version! ;)

Will try the new version .. thanks for the quick update on this..very much appreciated <3
,

**Comment by kentify** [comment]
@Oizaro and also in the vanced manager app.. i found a bug that when you tap multiple times install button.. the progress bar goes forward and backwards..

it maybe due to multiple download instance? can it be fixed by pressing the install button and make it unclickable right after?

thanks love your work and keep up (y) Cheers

**Comment by kentify** [comment]
@Oizaro I tried and I was surpised that it worked. WOW! can't believed it.. worth the wait ... THANK you very much <3 ..

https://add.pics/image/a5Qi2
https://add.pics/image/a5jGB

**Comment by Oizaro** [comment]
@kentify 

Report Manager bugs on Manager repository 👍

**Comment by kentify** [comment]
> @kentify
> 
> Report Manager bugs on Manager repository 👍

Oh i'll report it later.. i'll just verify if it still occur in my device.. thanks

**Comment by kentify** [comment]
> @kentify
> 
> Report Manager bugs on Manager repository 👍

Hi, I have friend that has a new firmware version than mine(EMUI 10.1.0.228) which is EMUI 10.1.0.236 .. 
when she tried to logged in... the same error occurred that says Sorry, cannot connect to google server.

is there any work around for this? it seem to be working just fine in version 228 but in version 236 and above .. the issue hasn't been fixed.

**Comment by Oizaro** [comment]
@kentify 

Ensure doesn't have Google Play Services installed, and reinstall new microg version (after uninstalling current).

**Comment by kentify** [comment]
> @kentify
> 
> Ensure doesn't have Google Play Services installed, and reinstall new microg version (after uninstalling current).

Does unistalling it may remove the GMS that was installed in it? because one mistake could lead to not having GMS anymore cause it was already patch by google

**Comment by Oizaro** [comment]
> > @kentify
> > Ensure doesn't have Google Play Services installed, and reinstall new microg version (after uninstalling current).
> 
> Does unistalling it may remove the GMS that was installed in it? because one mistake could lead to not having GMS anymore cause it was already patch by google

This patch it does not activate if gms are installed in the system, because this patch was mainly designed for new devices that do not have it (for example P40).

**Comment by kentify** [comment]
> This patch it does not activate if gms are installed in the system (they are detected by a check), because this patch was mainly designed for new devices that do not have it (for example P40).

she replied back to me that she doesn't have any Google play service installed. Now I'm confused

**Comment by Oizaro** [comment]
> > This patch it does not activate if gms are installed in the system (they are detected by a check), because this patch was mainly designed for new devices that do not have it (for example P40).
> 
> she replied back to me that she doesn't have any Google play service installed. Now I'm confused

Ok, try second tip so.

**Comment by kentify** [comment]
> > > This patch it does not activate if gms are installed in the system (they are detected by a check), because this patch was mainly designed for new devices that do not have it (for example P40).
> > 
> > 
> > she replied back to me that she doesn't have any Google play service installed. Now I'm confused
> 
> Ok, try second tip so.

the issue still persist.. i told her to reset her phone and waiting for her feedback.. hope it will be fix soon and if not i also hope it would be fixed in the next update .. becuase there's is not way to use youtube except for this app :( .. Thanks for the time :)

**Comment by kentify** [comment]
@Oizaro She tried to reset but same thing had happened.. This is maybe due to the security update on patch 10.1.0.236..
i think it's August 2020 android security patch :/ .. hope there will be a fix soon

**Comment by Oizaro** [comment]
@kentify Which device she had?

**Comment by Oizaro** [comment]
@kentify 

Try this package. I added a toggle named "mask brand model", to chose when you want to apply this fix without this activating itself.

https://mega.nz/file/ERFxwC5K#jfXwGBB8I0O2RchTGGFAw3oJiwyQ1WS3nnPsPJAjysw

**Comment by kentify** [comment]
> @kentify Which device she have?

Same as mine huawei nova 7i

> @kentify
> 
> Try this package. I added a toggle named "mask brand model", to chose when you want to apply this fix without this activating itself.
> 
> P.S: Enable toggle before log in.
> 
> https://mega.nz/file/dEsDDaIC#BeEd6uCCfRHpeuQHLJf_5jpd3mCJG4D76-4wC-8SRhk

okay I will get back to you once she tried it .. Appreciate it man .. thanks

**Comment by Oizaro** [comment]
> > @kentify Which device she have?
> 
> Same as mine huawei nova 7i
> 
> > @kentify
> > Try this package. I added a toggle named "mask brand model", to chose when you want to apply this fix without this activating itself.
> > P.S: Enable toggle before log in.
> > https://mega.nz/file/dEsDDaIC#BeEd6uCCfRHpeuQHLJf_5jpd3mCJG4D76-4wC-8SRhk
> 
> okay I will get back to you once she tried it .. Appreciate it man .. thanks

For completeness, test it on your phone too.

**Comment by kentify** [comment]
> > > @kentify Which device she have?
> > 
> > 
> > Same as mine huawei nova 7i
> > > @kentify
> > > Try this package. I added a toggle named "mask brand model", to chose when you want to apply this fix without this activating itself.
> > > P.S: Enable toggle before log in.
> > > https://mega.nz/file/dEsDDaIC#BeEd6uCCfRHpeuQHLJf_5jpd3mCJG4D76-4wC-8SRhk
> > 
> > 
> > okay I will get back to you once she tried it .. Appreciate it man .. thanks
> 
> For completeness, test it on your phone too.
> 
> This is a more flexible way, and could be potentially better than current.

okay will also try this version

**Comment by kentify** [comment]
@Oizaro this version is not working  .. tried enabling spoofing but has error that cannot google servers

**Comment by Oizaro** [comment]
> @Oizaro this version is not working .. tried enabling spoofing but has error that cannot google servers

So doesn't work for you?

**Comment by kentify** [comment]
> > @Oizaro this version is not working .. tried enabling spoofing but has error that cannot google servers
> 
> So doesn't work for you?

yep it doens't ... it says sorry, cannot communicate to google servers..

**Comment by Oizaro** [comment]
> > > @Oizaro this version is not working .. tried enabling spoofing but has error that cannot google servers
> > 
> > 
> > So doesn't work for you?
> 
> yep it doens't ... it says sorry, cannot communicate to google servers..

Ok, I will check better tomorrow.

**Comment by kentify** [comment]
> > > > @Oizaro this version is not working .. tried enabling spoofing but has error that cannot google servers
> > > 
> > > 
> > > So doesn't work for you?
> > 
> > 
> > yep it doens't ... it says sorry, cannot communicate to google servers..
> 
> Ok, I will check better tomorrow.

Thank :D I will be waiting for it

**Comment by kentify** [comment]
@Oizaro Hi :D good news .. the issue has been fixed!!!
She just hard reset it and the app is working just fine..
My suspicion was, she was try to install gms after she bought it but failed and forgot to uninstall the FRP bypass stuff.
It may have been in conflict with the microg and fail to bypass it.
Thanks for the effort man and I hope you guys the best .. Cheers!

**Comment by Oizaro** [comment]
> @Oizaro Hi :D good news .. the issue has been fixed!!!
> She just hard reset it and the app is working just fine..
> My suspicion was, she was trying to install GMS into her phone after she bought it but failed and forgot to uninstall the FRP bypass stuff.
> It may have been in conflict with the microg and fail to bypass it.
> Thanks for the effort man and I hope you guys the best .. Cheers!

Thanks for your tests, this shows that a toggle is needed after all.

**Comment by Oizaro** [comment]
@kentify I need you help to test this new build: https://mega.nz/file/MIsTGICC#MtURxgSTzWlaIXd-zI3EfV3tFMiyEaqRivINbQLfs7U

Try to log in after enable "mask model" toggle from microg settings.

**Comment by kentify** [comment]
Hi good day sir @Oizaro is there any fix regarding login error issue on Huawei devices with GMS installed? I managed to install GMS into my huawei nova 7i today and I tried installing vanced app after resetting my phone. The problem now is that since I have google services, I can't login into my account. Is there any temporary fix on this?

**Comment by Oizaro** [comment]
> Hi good day sir @Oizaro is there any fix regarding login error issue on Huawei devices with GMS installed? I managed to install GMS into my huawei nova 7i today and I tried installing vanced app after resetting my phone. The problem now is that since I have google services, I can't login into my account. Is there any temporary fix on this?

I have added a new button at login start, named "Huawei" (will be implemented on new version, soon). In this way you should be able to login with or without gcm.

**Comment by kentify** [comment]
> > Hi good day sir @Oizaro is there any fix regarding login error issue on Huawei devices with GMS installed? I managed to install GMS into my huawei nova 7i today and I tried installing vanced app after resetting my phone. The problem now is that since I have google services, I can't login into my account. Is there any temporary fix on this?
> 
> I have added a new button at login start, named "Huawei" (will be implemented on new version, soon). In this way you should be able to login with or without gcm.

Oh okay. thanks for the fast reply 👍 more power to you Sempai @Oizaro

**Comment by Oizaro** [comment]
> > > Hi good day sir @Oizaro is there any fix regarding login error issue on Huawei devices with GMS installed? I managed to install GMS into my huawei nova 7i today and I tried installing vanced app after resetting my phone. The problem now is that since I have google services, I can't login into my account. Is there any temporary fix on this?
> > 
> > 
> > I have added a new button at login start, named "Huawei" (will be implemented on new version, soon). In this way you should be able to login with or without gcm.
> 
> Oh okay. thanks for the fast reply 👍 more power to you Sempai @Oizaro

You found me now, because I'm working on MicroG in this moment xD.

**Comment by kentify** [comment]
> > > > Hi good day sir @Oizaro is there any fix regarding login error issue on Huawei devices with GMS installed? I managed to install GMS into my huawei nova 7i today and I tried installing vanced app after resetting my phone. The problem now is that since I have google services, I can't login into my account. Is there any temporary fix on this?
> > > 
> > > 
> > > I have added a new button at login start, named "Huawei" (will be implemented on new version, soon). In this way you should be able to login with or without gcm.
> > 
> > 
> > Oh okay. thanks for the fast reply 👍 more power to you Sempai @Oizaro
> 
> You found me now, because I'm working on MicroG in this moment xD.

Kudos to you Sempai @Oizaro 💯 More power to you xD  Best MOD ever 👍

**Comment by Oizaro** [comment]
@kentify 

Released. You'll find on release section here on github.

**Comment by kentify** [comment]
> @kentify
> 
> Released. You'll find on release section here on github.

Woah that was fast ❤️ .. I'll check now and test it .. Thanks sempai @Oizaro

**Comment by kentify** [comment]
> @kentify
> 
> Released. You'll find on release section here on github.

UPDATE: can't login from both Huawei and Signin.. Same error is thrown.. Sorry! cannot connect to google server.

**Comment by Oizaro** [comment]
> > @kentify
> > Released. You'll find on release section here on github.
> 
> UPDATE: can't login from both Huawei and Signin.. Same error is thrown.. Sorry! cannot connect to google server.

Tap on "Huawei" button

**Comment by kentify** [comment]
> > > @kentify
> > > Released. You'll find on release section here on github.
> > 
> > 
> > UPDATE: can't login from both Huawei and Signin.. Same error is thrown.. Sorry! cannot connect to google server.
> 
> Tap on "Huawei" button at login start.

It doesn't work still sempai 
![Screenshot_20201004_022125_com mgoogle android gms](https://user-images.githubusercontent.com/52382580/94998957-616cbd80-05e8-11eb-8db0-bc243f346cd3.jpg)
![Screenshot_20201004_022120_com mgoogle android gms](https://user-images.githubusercontent.com/52382580/94998963-6df11600-05e8-11eb-92a6-15009a3961ef.jpg)

**Comment by Oizaro** [comment]
@kentify I can't help you so, works for other testers. If you want join on discord group, in this way we could better helping you.

**Comment by kentify** [comment]
> @kentify I can't help you so, works for other testers. If you want join on discord group, in this way we could better helping you.

What is your discord group? I will join if i have time :D

**Comment by Oizaro** [comment]
> > @kentify I can't help you so, works for other testers. If you want join on discord group, in this way we could better helping you.
> 
> What is your discord group? I will join if i have time :D

https://vanced.app/discord

**Comment by kentify** [comment]
> > > @kentify I can't help you so, works for other testers. If you want join on discord group, in this way we could better helping you.
> > 
> > 
> > What is your discord group? I will join if i have time :D
> 
> https://vanced.app/discord

Okay thanks. will catch up to you later :D Power Blackout today so need to charge up my devices

**Comment by Oizaro** [comment]
@kentify Don't spam on others issue reports. I already told what you do:

> I can't help you so, works for other testers. If you want join on discord group, in this way we could better helping you.

**Comment by kevinbakbak** [comment]
> @kentify
> 
> Login issue fix for Huawei/Honor or Any other device users
> Solution:
> 
> Workaround 1: (Credit: Leszek1337 from reddit)
> 
> 1. First install the old microG version (remove the current one installed but keep the apk for it - you need it later).
> 
> microg_YouTube_Vanced_0.2.4-105_16052019_2.apk (get from the old files link on vanced.app site)
> 
> 1. Then open YouTube Vanced and try loging in again until it shows the error message. Try to at least ones reload it by tapping the error message.
> 2. Now install the newer microG version again and restart vanced. It should be logged in again and everything should work again.
> 
> NOTE: Now make sure u disable battery optimization for both microg and vanced using dontkillmyapp.com otherwise your device software might kill microg and you might have to repeat all above steps again to fix login.
> 
> Workaround 2: (this is most likely to work so try this first)
> 
> 1. Remove microg then reinstall it.
> 2. Then open microg app settings (use either activity launcher or open from vanced app settings) and turn off google cloud messaging and google device registration.
> 3. Add your account and enjoy

谢谢，第二种方法可行😁
