### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [YTVanced/VancedMicroG#46]
Hi @YTVanced

Since this app is Apache V2 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? It could be useful for some of us.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if one of our packager takes care of this?

**Comment by KevinX8** [comment]
You can maintain it on fdroid if you wish, we update it using vanced manager anyhow.
