### ISSUE TITLE
Latest version of VancedMicroG is adding extra devices to Google Account

### ISSUE THREAD

**Issue by fosam** [YTVanced/VancedMicroG#48]
Hi!

Thanks for the latest version of VancedMicroG.

But the issue with this latest version is it is creating extra device(s) on Google account when a user logs into VancedMicroG **v0.2.12** on a device.

After some testing i found out that version **v0.2.11** released jul 29 does not cause this issue as it is not creating any extra device on my Google account.

![Capture 23_09_2020_19_49_11](https://user-images.githubusercontent.com/52612348/94050847-19bf8800-fdd7-11ea-8101-ddc69d95f147.png)

As you can see in the screenshot when i manually signed out of the extra devices by clicking the three dots and "sign out" they got moved to the "Where you’ve signed out" section.

When i switched back to VancedMicroG v0.2.11 then only one device is showing as the above part of the screenshot.

I almost signed out of my actual Google account as i did not know what was VancedMicroG and what was the Google account.

The test is from today even if on one device says Sep 2.

For now i'll just still be using v0.2.11 as it is not confusing me by creating duplicate devices in my Google account.

Why in your opinion does VancedMicroG create a duplicate device on the account? and v0.2.11 does not?

Thanks!

**Comment by Oizaro** [comment]
On latest version 0.2.12 the login code was changed by the lead author of microg (which is not us on this repo). I guess this is the cause of multiple listed devices.

**Comment by fosam** [comment]
Guess we have to try on the next release then..

**Comment by Oizaro** [comment]
> Guess we have to try on the next release then..

Assuming it's not normal behavior.

**Comment by pushkargogte** [comment]
https://github.com/YTVanced/Vanced/issues/52
