### ISSUE TITLE
What is the Huawei login about

### ISSUE THREAD

**Issue by MKCOOL142** [YTVanced/VancedMicroG#49]
I'd like to know why it's there and what difference it has to the regular login method, is it only for devices that don't have GMS or is it recommended for me to use even if I have the official GMS pre-installed

**Comment by Oizaro** [comment]
The only difference is that you can log in without errors. If normal access is giving you trouble, use this.

**Comment by MKCOOL142** [comment]
Okay, but if I have GMS already I shouldn't have any issue?

**Comment by Oizaro** [comment]
> Okay, but if I have GMS already I shouldn't have any issue?

I don't know, let's try it (uninstall previous version before).

**Comment by kentify** [comment]
> > Okay, but if I have GMS already I shouldn't have any issue?
> 
> I don't know, let's try it (uninstall previous version before).

Hey sempai @Oizaro it seems that the new update doesn't work anymore.
I tried resetting my phone and now without GMS.. i tried adding an account on but its seem that the error persist,

**Comment by kentify** [comment]
@Oizaro it seems that the latest version is not working for me but when I downloaded Vanced MicroG v0.2.12. It worked like charm.
