### ISSUE TITLE
Couldn't login to account with 2FA enabled

### ISSUE THREAD

**Issue by sdescarries** [YTVanced/VancedMicroG#52]
Tried multiple times to no avail until I resorted to temporarily disable two factor authentication. On my device the 2FA would pop the verification screen right after entering the password, seemingly messing up with the login flow in microG.

```
microG v0.2.13.203916
Samsung A31
Android 10
```

**Comment by Oizaro** [comment]
Hi.

At the moment there isn't a solution for this problem.

**Comment by X1nto** [comment]
Could you please re-check this with the latest microG? 2FA works fine for me

**Comment by Monir966** [comment]
It's not connecting infinix hot 10

**Comment by milindgoel15** [comment]
2-factor authentication works fine as of the latest vanced microG release as well. If you are still facing issues with it, feel free to provide further details on your problem. Closing this issue for now.
