### ISSUE TITLE
Can't install v0.2.13-203916 on Android 5.1.1

### ISSUE THREAD

**Issue by DroidSFT** [YTVanced/VancedMicroG#53]
When I try to install v0.2.13-203916 on Android 5.1.1 manually, it fails with the following alert: "Parse error. There was a problem parsing the package". When I try to install it using VancedManager, it shows: "Error. Installation failed because the apk files are corrupted, please try again".
There's no such issue with this apk on newer Android versions.
Also I'm able to install the previous version 0.2.13-203915 on this Android 5.1.1 device without any issues.

**Comment by Oizaro** [comment]
Fixed.
