### ISSUE TITLE
Standard and Vanced microg together on huawei devices

### ISSUE THREAD

**Issue by michael1900** [YTVanced/VancedMicroG#58]
Last microg vanced version cannot be installed together this standard microg, but huawei users like me without google services need both mircog, standard and vanced. Ho w fix this?

**Comment by Kroissan** [comment]
Hey, same here, just got p40 pro. Do you know if it worked previously ? If so with wich version ?
![eror](https://user-images.githubusercontent.com/66138267/100284856-2c3d7580-2f70-11eb-84f8-cf0a9a9be0b3.PNG)

**Comment by mikken** [comment]
Same problem here.
I use LineageOS for microG (fork of LineageOS with microG pre-installed).
0.2.13-203916 installs fine, 0.2.14 can't be installed (both manually or with Vanced Manager).

**Comment by michael1900** [comment]
> Hey, same here, just got p40 pro. Do you know if it worked previously ? If so with wich version ?
> ![eror](https://user-images.githubusercontent.com/66138267/100284856-2c3d7580-2f70-11eb-84f8-cf0a9a9be0b3.PNG)

0.2.13-203916

**Comment by michael1900** [comment]
Look at last push code, the package is named again in com.google.android.gms and not more in com.mgoogle.android.gms

This is the big problem, i don't know why devs haven't fixed that.

From official readme:

- **Package name changed from ### com.google.android.gms to ### com.mgoogle.android.gms to support installation alongside the official MicroG**

**Comment by michael1900** [comment]
Where are the devs? They are still here?

**Comment by Oizaro** [comment]
> Where are the devs? They are still here?

On Discord channel.

**Comment by michael1900** [comment]
> > Where are the devs? They are still here?
> 
> On Discord server:
> 
> https://discord.com/invite/K9KKDqd

I prefer here. Hope they fix this awful problem.

**Comment by Oizaro** [comment]
> > > Where are the devs? They are still here?
> > 
> > 
> > On Discord server:
> > https://discord.com/invite/K9KKDqd
> 
> I prefer here. Hope you can fix this awful problem.
> 
> From readme:
> 
> Package name changed from com.google.android.gms to com.mgoogle.android.gms to support installation alongside the official MicroG

I was the mainteiner of this repository. But now I deceided to stop the works on this, because I'm tired of update MicroG.

There's no dev here apart me, so ask support on discord channel.

**Comment by michael1900** [comment]
> > > > Where are the devs? They are still here?
> > > 
> > > 
> > > On Discord server:
> > > https://discord.com/invite/K9KKDqd
> > 
> > 
> > I prefer here. Hope you can fix this awful problem.
> > From readme:
> > Package name changed from com.google.android.gms to com.mgoogle.android.gms to support installation alongside the official MicroG
> 
> I was the mainteiner of this repository. **But now I deceided to stop the works on this,** because I'm tired of update MicroG.
> 
> There's no dev here apart me, so ask support on discord channel. Otherwise you will be ignored.

Oh God! :(

**Comment by Oizaro** [comment]
> > > > > Where are the devs? They are still here?
> > > > 
> > > > 
> > > > On Discord server:
> > > > https://discord.com/invite/K9KKDqd
> > > 
> > > 
> > > I prefer here. Hope you can fix this awful problem.
> > > From readme:
> > > Package name changed from com.google.android.gms to com.mgoogle.android.gms to support installation alongside the official MicroG
> > 
> > 
> > I was the mainteiner of this repository. **But now I deceided to stop the works on this,** because I'm tired of update MicroG.
> > There's no dev here apart me, so ask support on discord channel. Otherwise you will be ignored.
> 
> Oh God! :(

Ooook...I hate to leave something incomplete, so I have however fixed the bug. 👍

**Comment by Oizaro** [comment]
> > > > > Where are the devs? They are still here?
> > > > 
> > > > 
> > > > On Discord server:
> > > > https://discord.com/invite/K9KKDqd
> > > 
> > > 
> > > I prefer here. Hope you can fix this awful problem.
> > > From readme:
> > > Package name changed from com.google.android.gms to com.mgoogle.android.gms to support installation alongside the official MicroG
> > 
> > 
> > I was the mainteiner of this repository. **But now I deceided to stop the works on this,** because I'm tired of update MicroG.
> > There's no dev here apart me, so ask support on discord channel. Otherwise you will be ignored.
> 
> Oh God! :(

Try this package:

https://mega.nz/file/IJEQwDbb#A5XLyIguXWd7EEDuG-GZ-wHh2S8ZRJRZdlj6yzUDRaQ

**Comment by michael1900** [comment]
> > > > > > Where are the devs? They are still here?
> > > > > 
> > > > > 
> > > > > On Discord server:
> > > > > https://discord.com/invite/K9KKDqd
> > > > 
> > > > 
> > > > I prefer here. Hope you can fix this awful problem.
> > > > From readme:
> > > > Package name changed from com.google.android.gms to com.mgoogle.android.gms to support installation alongside the official MicroG
> > > 
> > > 
> > > I was the mainteiner of this repository. **But now I deceided to stop the works on this,** because I'm tired of update MicroG.
> > > There's no dev here apart me, so ask support on discord channel. Otherwise you will be ignored.
> > 
> > 
> > Oh God! :(
> 
> Try this package:
> 
> https://mega.nz/file/IJEQwDbb#A5XLyIguXWd7EEDuG-GZ-wHh2S8ZRJRZdlj6yzUDRaQ

**Stunning! It works with no problem. Installed together vanilla version.**

**Thank you!**

I need an advice, this thing also with previous versions. I have the vanced notifications about battery optimization but when i try to search vanced microg this doesn't appear so nothing can be done. The standard microg instead is in the list.
Can be this a problem?

**Comment by Oizaro** [comment]
> > > > > > > Where are the devs? They are still here?
> > > > > > 
> > > > > > 
> > > > > > On Discord server:
> > > > > > https://discord.com/invite/K9KKDqd
> > > > > 
> > > > > 
> > > > > I prefer here. Hope you can fix this awful problem.
> > > > > From readme:
> > > > > Package name changed from com.google.android.gms to com.mgoogle.android.gms to support installation alongside the official MicroG
> > > > 
> > > > 
> > > > I was the mainteiner of this repository. **But now I deceided to stop the works on this,** because I'm tired of update MicroG.
> > > > There's no dev here apart me, so ask support on discord channel. Otherwise you will be ignored.
> > > 
> > > 
> > > Oh God! :(
> > 
> > 
> > Try this package:
> > https://mega.nz/file/IJEQwDbb#A5XLyIguXWd7EEDuG-GZ-wHh2S8ZRJRZdlj6yzUDRaQ
> 
> **Stunning! It works with no problem. Installed together vanilla version.**
> 
> **Thank you!**
> 
> I need an advice, this thing also with previous versions. I have the vanced notifications about battery optimization but when i try to search vanced microg this doesn't appear so nothing can be done. The standard microg instead is in the list.
> Can be this a problem?

If you don't disable the optimization you may have problems to receiving notifications from Youtube. That's why there's always a message that suggests you to turn off optimization.

In every case idk how to fix this problem without enable microg icon on home launcher (I guess Huawei need of this to add an app to the list).

**Comment by michael1900** [comment]
> > > > > > > > Where are the devs? They are still here?
> > > > > > > 
> > > > > > > 
> > > > > > > On Discord server:
> > > > > > > https://discord.com/invite/K9KKDqd
> > > > > > 
> > > > > > 
> > > > > > I prefer here. Hope you can fix this awful problem.
> > > > > > From readme:
> > > > > > Package name changed from com.google.android.gms to com.mgoogle.android.gms to support installation alongside the official MicroG
> > > > > 
> > > > > 
> > > > > I was the mainteiner of this repository. **But now I deceided to stop the works on this,** because I'm tired of update MicroG.
> > > > > There's no dev here apart me, so ask support on discord channel. Otherwise you will be ignored.
> > > > 
> > > > 
> > > > Oh God! :(
> > > 
> > > 
> > > Try this package:
> > > https://mega.nz/file/IJEQwDbb#A5XLyIguXWd7EEDuG-GZ-wHh2S8ZRJRZdlj6yzUDRaQ
> > 
> > 
> > **Stunning! It works with no problem. Installed together vanilla version.**
> > **Thank you!**
> > I need an advice, this thing also with previous versions. I have the vanced notifications about battery optimization but when i try to search vanced microg this doesn't appear so nothing can be done. The standard microg instead is in the list.
> > Can be this a problem?
> 
> If you don't disable the optimization you may have problems to receiving notifications from Youtube. That's why there's always a message that suggests you to turn off optimization.
> 
> In every case idk how to fix this problem without enable microg icon on home launcher (I guess Huawei need of this to add an app to the list).

I think to have understood but i am not sure about last period. 
The icon of vanced microg is on home launcher so this is right, like with vanilla microg. But the problem with that notification is that there is not vanced microg app in the list of app to optimize. There is only standard microg. 

I remember that some versions ago vanced microg was in the list and we could deactivate the battery optimization. So maybe it's a bug, i don't know honestly. Still thanks!

**Comment by Oizaro** [comment]
> > > > > > > > > Where are the devs? They are still here?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > On Discord server:
> > > > > > > > https://discord.com/invite/K9KKDqd
> > > > > > > 
> > > > > > > 
> > > > > > > I prefer here. Hope you can fix this awful problem.
> > > > > > > From readme:
> > > > > > > Package name changed from com.google.android.gms to com.mgoogle.android.gms to support installation alongside the official MicroG
> > > > > > 
> > > > > > 
> > > > > > I was the mainteiner of this repository. **But now I deceided to stop the works on this,** because I'm tired of update MicroG.
> > > > > > There's no dev here apart me, so ask support on discord channel. Otherwise you will be ignored.
> > > > > 
> > > > > 
> > > > > Oh God! :(
> > > > 
> > > > 
> > > > Try this package:
> > > > https://mega.nz/file/IJEQwDbb#A5XLyIguXWd7EEDuG-GZ-wHh2S8ZRJRZdlj6yzUDRaQ
> > > 
> > > 
> > > **Stunning! It works with no problem. Installed together vanilla version.**
> > > **Thank you!**
> > > I need an advice, this thing also with previous versions. I have the vanced notifications about battery optimization but when i try to search vanced microg this doesn't appear so nothing can be done. The standard microg instead is in the list.
> > > Can be this a problem?
> > 
> > 
> > If you don't disable the optimization you may have problems to receiving notifications from Youtube. That's why there's always a message that suggests you to turn off optimization.
> > In every case idk how to fix this problem without enable microg icon on home launcher (I guess Huawei need of this to add an app to the list).
> 
> I think to have understood but i am not sure about last period.
> The icon of vanced microg is on home launcher so this is right, like with vanilla microg. But the problem with that notification is that there is not vanced microg app in the list of app to optimize. There is only standard microg.
> 
> I remember that some versions ago vanced microg was in the list and we could deactivate the battery optimization. So maybe it's a bug, i don't know honestly. Still thanks!

Technically shouldn't, because I removed the icon code from manifest xD (and indeed this doesn't shown in practically every case).

EMUI works in a way that I don't understand.

**Comment by michael1900** [comment]
> > > > > > > > > > Where are the devs? They are still here?
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > On Discord server:
> > > > > > > > > https://discord.com/invite/K9KKDqd
> > > > > > > > 
> > > > > > > > 
> > > > > > > > I prefer here. Hope you can fix this awful problem.
> > > > > > > > From readme:
> > > > > > > > Package name changed from com.google.android.gms to com.mgoogle.android.gms to support installation alongside the official MicroG
> > > > > > > 
> > > > > > > 
> > > > > > > I was the mainteiner of this repository. **But now I deceided to stop the works on this,** because I'm tired of update MicroG.
> > > > > > > There's no dev here apart me, so ask support on discord channel. Otherwise you will be ignored.
> > > > > > 
> > > > > > 
> > > > > > Oh God! :(
> > > > > 
> > > > > 
> > > > > Try this package:
> > > > > https://mega.nz/file/IJEQwDbb#A5XLyIguXWd7EEDuG-GZ-wHh2S8ZRJRZdlj6yzUDRaQ
> > > > 
> > > > 
> > > > **Stunning! It works with no problem. Installed together vanilla version.**
> > > > **Thank you!**
> > > > I need an advice, this thing also with previous versions. I have the vanced notifications about battery optimization but when i try to search vanced microg this doesn't appear so nothing can be done. The standard microg instead is in the list.
> > > > Can be this a problem?
> > > 
> > > 
> > > If you don't disable the optimization you may have problems to receiving notifications from Youtube. That's why there's always a message that suggests you to turn off optimization.
> > > In every case idk how to fix this problem without enable microg icon on home launcher (I guess Huawei need of this to add an app to the list).
> > 
> > 
> > I think to have understood but i am not sure about last period.
> > The icon of vanced microg is on home launcher so this is right, like with vanilla microg. But the problem with that notification is that there is not vanced microg app in the list of app to optimize. There is only standard microg.
> > I remember that some versions ago vanced microg was in the list and we could deactivate the battery optimization. So maybe it's a bug, i don't know honestly. Still thanks!
> 
> Technically shouldn't, because I removed the icon code from manifest xD (and indeed this doesn't shown in practically every case).
> 
> Maybe it's a bug, I don't know. EMUI works in a way that I don't understand.

So weird. About "Technically shouldn't" you mean that vanced microg icon on home launcher shouldn't appear although in my case it appears?

**Comment by Oizaro** [comment]
Exactly... Indeed this doesn't shown to me.

**Comment by michael1900** [comment]
> Exactly... Indeed this doesn't shown to me.

As a last thing can you add again the icon code from manifest so we can also defeat this last bug about vanced microg app missing in optimization battery app list?
Please and thanks man ;)

**Comment by Oizaro** [comment]
> > Exactly... Indeed this doesn't shown to me.
> 
> As a last thing can you add again the icon code from manifest so we can also defeat this last bug about vanced microg app missing in optimization battery app list? That notifications will make sense again.
> Please and thanks man ;)

I can't, because otherwise everyone will get back the home launcher icon.

**Comment by michael1900** [comment]
Ok man, understtod. But i think this is not a good choice, not only for huawei, **to deactivate battery optimization** just as that notification indicates. Indeed there isn't this problem on vanilla microg. App appears in home launcher and in battery optimization list like should.
Then, in my case with huawei, the home launcher still appears so it's a bit non sense. 
Btw think about it if you can because I believe that this choice not to make the icon appears in home launcher can compromise the deactivation of battery optimization for vanced micro g!

Thanks man for support.

**Comment by Jellybean-Sandwich** [comment]
> 
> 
> > > > > > Where are the devs? They are still here?
> > > > > 
> > > > > 
> > > > > On Discord server:
> > > > > https://discord.com/invite/K9KKDqd
> > > > 
> > > > 
> > > > I prefer here. Hope you can fix this awful problem.
> > > > From readme:
> > > > Package name changed from com.google.android.gms to com.mgoogle.android.gms to support installation alongside the official MicroG
> > > 
> > > 
> > > I was the mainteiner of this repository. **But now I deceided to stop the works on this,** because I'm tired of update MicroG.
> > > There's no dev here apart me, so ask support on discord channel. Otherwise you will be ignored.
> > 
> > 
> > Oh God! :(
> 
> Try this package:
> 
> https://mega.nz/file/IJEQwDbb#A5XLyIguXWd7EEDuG-GZ-wHh2S8ZRJRZdlj6yzUDRaQ

The link to the fix says the file is no longer available

**Comment by Oizaro** [comment]
> > > > > > > Where are the devs? They are still here?
> > > > > > 
> > > > > > 
> > > > > > On Discord server:
> > > > > > https://discord.com/invite/K9KKDqd
> > > > > 
> > > > > 
> > > > > I prefer here. Hope you can fix this awful problem.
> > > > > From readme:
> > > > > Package name changed from com.google.android.gms to com.mgoogle.android.gms to support installation alongside the official MicroG
> > > > 
> > > > 
> > > > I was the mainteiner of this repository. **But now I deceided to stop the works on this,** because I'm tired of update MicroG.
> > > > There's no dev here apart me, so ask support on discord channel. Otherwise you will be ignored.
> > > 
> > > 
> > > Oh God! :(
> > 
> > 
> > Try this package:
> > https://mega.nz/file/IJEQwDbb#A5XLyIguXWd7EEDuG-GZ-wHh2S8ZRJRZdlj6yzUDRaQ
> 
> The link to the fix says the file is no longer available

Soon will be available on manager.

**Comment by michael1900** [comment]
> > > > > > > > Where are the devs? They are still here?
> > > > > > > 
> > > > > > > 
> > > > > > > On Discord server:
> > > > > > > https://discord.com/invite/K9KKDqd
> > > > > > 
> > > > > > 
> > > > > > I prefer here. Hope you can fix this awful problem.
> > > > > > From readme:
> > > > > > Package name changed from com.google.android.gms to com.mgoogle.android.gms to support installation alongside the official MicroG
> > > > > 
> > > > > 
> > > > > I was the mainteiner of this repository. **But now I deceided to stop the works on this,** because I'm tired of update MicroG.
> > > > > There's no dev here apart me, so ask support on discord channel. Otherwise you will be ignored.
> > > > 
> > > > 
> > > > Oh God! :(
> > > 
> > > 
> > > Try this package:
> > > https://mega.nz/file/IJEQwDbb#A5XLyIguXWd7EEDuG-GZ-wHh2S8ZRJRZdlj6yzUDRaQ
> > 
> > 
> > The link to the fix says the file is no longer available
> 
> Soon will be available on manager.

Hi Man, can you make a different build to post (only) here with that icon code in manifest?

**Comment by Oizaro** [comment]
@michael1900 Uninstall previous and install this:

https://mega.nz/file/8Z8GhDjB#RwL_uAipR8JACzK-YrkkICe4WGxEOJaCM0vYoWcGcJc

**Comment by michael1900** [comment]
> @michael1900 Done. Uninstall previous and install this:
> 
> https://mega.nz/file/8Z8GhDjB#RwL_uAipR8JACzK-YrkkICe4WGxEOJaCM0vYoWcGcJc


Stunning job Man. ALL fixed. Hope this mod will be in official repo with new devs. 

Thanks again!

**Comment by Oizaro** [comment]
> > @michael1900 Done. Uninstall previous and install this:
> > https://mega.nz/file/8Z8GhDjB#RwL_uAipR8JACzK-YrkkICe4WGxEOJaCM0vYoWcGcJc
> 
> Stunning job Man. ALL fixed. Hope this mod will be in official repo with new devs.
> 
> Thanks again!

Unfortunately not. At least not in this form. I temoved this icon because was useless (indeed manager already give the possibility to access to vanced microg settings).

**Comment by vladimir-tikhonov** [comment]
@Oizaro could you please upload the apk once again? Perhaps not to mega, because it continue to remove it :)

**Comment by KevinX8** [comment]
Fixed in latest release
