### ISSUE TITLE
MicroG fails to connect to Google server

### ISSUE THREAD

**Issue by GhostyJade** [YTVanced/VancedMicroG#59]
With the latest version of VancedMicroG, when I try to add a new account, it says that it can't connect to the google server (and "please try again later")

I'm using the latest version on a non root phone.

**Comment by lerg96** [comment]
Me too, nobody have a solution?

**Comment by nntu** [comment]
![Screenshot_20201222-072046_Vanced microG](https://user-images.githubusercontent.com/316238/102834309-427f0a00-4426-11eb-8ff5-60413dacb13d.jpg)

**Comment by lerg96** [comment]
i found that my problem is trying to sign in with a hotmail account (i have a Google account with hotmail, i can add this account to my phone to recovery photos and contacts but it's not working with microg, despite it was working before formating my phone)

**Comment by Vendicated** [comment]
MicroG works fine, the issue is on your end. If you're still experiencing issues please follow the [troubleshooting guide](https://telegra.ph/Troubleshooting-for-vanced-03-19)
