### ISSUE TITLE
Same build number issue

### ISSUE THREAD

**Issue by matke-84** [YTVanced/VancedMicroG#63]
You put the same build number as the original microg. I see it was corrected 4 days ago but you didn't release it publicly. Please update, I can't install since I already have a regular microg installed. Thanks in advance.

**Comment by KevinX8** [comment]
vanced microg has a different package id than stock microg so this should not matter? Not sure why you posted this.

**Comment by matke-84** [comment]
Because I can't install it on my tablet. I have noticed that so far it has always been one number larger than a regular microg. All versions have worked without problems so far. Why can't I install it now?

**Comment by matke-84** [comment]
Fixed. I don't know what the problem was, but now it's working, with one number bigger build. ;-) Thanks.
