### ISSUE TITLE
Can't disable battery optimizations (conflict w/ MicroG core)

### ISSUE THREAD

**Issue by Ken9449** [YTVanced/VancedMicroG#74]
Having MicroG core and Vanced MicroG installed conflicts in the battery optimizations settings on Huawei.
Meaning you can't disable battery optimizations, so notifications aren't working despite everything else being set up and connected.
Huawei P40
![Screenshot_20201209_172858](https://user-images.githubusercontent.com/49352931/101657433-2ce00c80-3a44-11eb-819d-4f39352f1737.jpg)
![Screenshot_20201209_172911](https://user-images.githubusercontent.com/49352931/101657440-2ea9d000-3a44-11eb-94b1-ee84ea6b4eae.jpg)

**Comment by Oizaro** [comment]
Fixed on 0.2.14.204218

**Comment by michael1900** [comment]
Finally fixed! Thank you!

**Comment by Ken9449** [comment]
Fixed!
