### ISSUE TITLE
VancedMicroG doesn't give storage permission by default which causes YTVanced to crash over and over

### ISSUE THREAD

**Issue by Kainetrt** [YTVanced/VancedMicroG#80]
I am using a Vivo IQOO 5 with android 10 non rooted device, i installed VancedManager and then proceed to install VancedMicroG, login to account,and install YTVanced. The first time i open YTVanced it works perfectly, if i don't kill the app, it keeps working perfectly. But if i kill the app and try to open it, the vanced logo pops up and the app close by himself. I tried this with different version of YTVanced and VancedMicroG and the result was always the same, it kept crashing after the first time you open the app. And i figured that it was because VancedMicroG hadn't storage permissions and that it needed to be manually set to "allow". Once the permission is given, the app works as it is supposed to work.

**Comment by AinzTheSupremeOne** [comment]
Bruh why are you even killing the app. It's supposed to run all the time. There is a reason why it needs battery optimization to be disabled, to prevent system from auto killing it. And storage permission can't be granted automatically. You have to manually do it.
