### ISSUE TITLE
Vanced microG doesn't connect to Google servers anymore.

### ISSUE THREAD

**Issue by alexceltare2** [YTVanced/VancedMicroG#83]
As the title says, I wasn't able to log into my account anymore. Must've been a change in the way GMS talks to Google account servers. YouTube Vanced works fine on the other hand. Latest YT and microG already installed on my Android 7.0 device.

**Comment by Firwana** [comment]
Had same issue today and still

**Comment by Vendicated** [comment]
MicroG works fine, the issue is on your end. If you're still experiencing issues please follow the [troubleshooting guide](https://telegra.ph/Troubleshooting-for-vanced-03-19)

**Comment by alexceltare2** [comment]
No, it wasn't on my end. It worked after an update of microG. Thanks for closing the issue anyway.
