### ISSUE TITLE
Issue with Google G-suit account

### ISSUE THREAD

**Issue by norouzimahalli** [YTVanced/VancedMicroG#86]
I have my G-suit account with my domain and one classic Gmail account. 

For the first time, I can login with both accounts even with 2 step authentication on, but after the first time, next time when I come back to YouTube Vanced it say no internet connection and retry to login for my G-suit account, the classic google account works fine thought.

But since the G-suit account is my main account I was wondering if there is a workaround to make it work or not.

I have to clear microg data everytime to make it work each time I open youtube Vanced.

**Comment by Vendicated** [comment]
https://github.com/YTVanced/Vanced/issues/394#issuecomment-769278619
