### ISSUE TITLE
Login not working after last update

### ISSUE THREAD

**Issue by uaibo** [YTVanced/VancedMicroG#87]
After January 28th update of the YouTube Vanced app and MicroG the login would not work anymore.
I'd enter Google account logins, it would seemingly go well but the account would not be added and also after that, the YouTube app wouldn't work normally (buttons "Explore", "Subscriptions", "Library" sometimes would not work at all when clicked etc). 

I had to find previous APKs from APK Mirror and install them both for YouTube and MicroG for login to work again.
Check below for my current working versions. 
![Screenshot_20210130-192007_Vanced Manager](https://user-images.githubusercontent.com/19323835/106364592-6c362580-6330-11eb-8664-631e3546c8b9.png)

I'm using Samsung Galaxy A71 with the following software
![Screenshot_20210130-192129_Settings](https://user-images.githubusercontent.com/19323835/106364603-7bb56e80-6330-11eb-847f-93b18da71fcb.png)

**Comment by gghhkm** [comment]
This is an upstream issue; so close this and go here:
https://github.com/microg/GmsCore/issues/1373

Here is the solution.
![temp-01](https://user-images.githubusercontent.com/72711094/106367604-d2f81680-6311-11eb-8aa3-ca34f964d7a7.jpg)

**Comment by uaibo** [comment]
Thanks @gghhkm that fixed the issue 👍
