### ISSUE TITLE
When using always-on VPN, the Google Account seems to be logged out upon location change

### ISSUE THREAD

**Issue by tursi960** [YTVanced/VancedMicroG#90]
**Problem:**
I've noticed that every 12 hours or so the Vanced Apps stopped working while using always-on VPN. 

**I'm using:**
Latest MicroG
Pixel 4A @ Android 11
PIA VPN @ Always-on VPN

**What I've tried:**
Reinstalling Vanced Music / Youtube each. (negative)
Creating an exception for all Vanced Apps in PIA. (negative)
Changing a bunch of setting like DNS / protocol in PIA. (negative)
Turning off PIA. (worked)
Reinstalling all apps, and signing in again with 2FA (worked)

I have the suspicion that it probably has something to do with 2FA because every time a device is added on my Google Account.

![Screenshot_20210201-021218](https://user-images.githubusercontent.com/35008962/106466477-a5d76f80-649b-11eb-93e7-4e2d8982bb47.png)

**Comment by Vendicated** [comment]
Please move this issue to [microg/gmsCore](https://github.com/microg/gmsCore) as this seems to be related to microg. Don't mention Vanced as they don't have anything to do with vanced, simply describe the issue you're having
