### ISSUE TITLE
#Bug

### ISSUE THREAD

**Issue by Brillianvo** [YTVanced/VancedMicroG#93]
#Bug hi I want to report a bug, where when I have registered my google account to microG my account is not readable in the microG and YouTube vanced application, so I can't enter YouTube, it only loads in the home section, how do I fix this ?, I've tried all the suggestions in the guid but none of them work and I've tried it on two different devices but the results are the same, even though I've used the latest version of the app, and I've also checked in the account manager on my device and my account is registered on microG, but when I try to see it in the microG application but it can't be read, please fix this problem immediately because it's very annoying 😢😢😢😢😢

**Comment by Brillianvo** [comment]
Indonesia
Inggris
hai saya ingin melaporkan sebuah bug, dimana saat saya sudah mendaftar kan akun google saya ke microG akun saya tidak terbaca di aplikasi microG dan YouTube vanced, sehingga saya tidak bisa masuk ke dalam YouTube dia hanya loading di bagian home saja bagaimana cara memperbaiki ini ?, saya sudah mencoba semua saran di guid tapi tidak ada satupun yang berhasil dan saya sudah mencoba nya di dua perangkat berbeda tapi hasilnya sama, padahal saya sudah memakai aplikasi versi terbaru, dan juga saya sudah mengecek di pengelola akun di perangkat saya dan akun saya sudah terdaftar di microG, tapi saat saya mencoba melihatnya di aplikasi microG namun tidak terbaca, mohon segera memperbaiki masalah ini soalnya ini sangat menggangu 😢😢😢😢😢
hi I want to report a bug, where when I have registered my google account to microG my account is not readable in the microG and YouTube vanced application, so I can't enter YouTube, it only loads in the home section, how do I fix this ?, I've tried all the suggestions in the guid but none of them work and I've tried it on two different devices but the results are the same, even though I've used the latest version of the app, and I've also checked in the account manager on my device and my account is registered on microG, but when I try to see it in the microG application but it can't be read, please fix this problem immediately because it's very annoying 😢😢😢😢😢

**Comment by PrinceMahe** [comment]
Having same issue, found any fix yet ?

**Comment by Vendicated** [comment]
check the pinned issue in https://github.com/YTVanced/Vanced
