### ISSUE TITLE
Vanced MicroG/Vanced Account Swapping 

### ISSUE THREAD

**Issue by SuperPatriotFan** [YTVanced/VancedMicroG#94]
So, when I go to switch to a different account through the Vanced app or with MicroG I encounter an issue where it won't display my other connected accounts on Vanced. And the last few times MicroG won't display the Google Sign-in screen/page.

**Comment by kalliyuga** [comment]
I'm also not able to update YT Music and MicroG is not able to add account. In Youtube Vanced, the account added is not shown in manage account. Also there's delay in opening and accessing youtube, sometimes I get an error: no network connection RETRY.

**Comment by DarkJester89** [comment]
MicroG is also doing this with my account. The screenshot is when I try to login through microG
![image](https://user-images.githubusercontent.com/79059318/107887168-1b96fe80-6ed2-11eb-9769-4c1f3dac438a.png)

**Comment by EchoRage25** [comment]
I am having the same problem. Assuming it has something do with me having the YouTube vanced and YouTube music vanced both downloaded but obviously only microG once.. idk. Might only let you be logged into your YouTube account on one or the other. Not both at the same time. :( 
![Screenshot_20210215-091527](https://user-images.githubusercontent.com/79103129/107971634-f48f0a00-6f6f-11eb-8106-f0ef379b9b33.png)

**Comment by TG310** [comment]
![IMG_20210221_224140](https://user-images.githubusercontent.com/52592373/108630162-0869cd00-7496-11eb-9927-9cc0cddbd016.jpg)
Yeah same problem here

**Comment by JeremyLaurent** [comment]
I'm having the exact same issue. At first I couldn't switch between my youtube accounts so I tried to remove them for vancedMicroG and now I can't add any account. It says that the account already exist even though it's not there. Reseting vancedMicroG and adding the account again doesn't seem to fix it even though it lets you add it. 

I'm on Vanced MicroG v0.2.16.204713 non Root on a One plus 6

**Comment by gghhkm** [comment]
This is an upstream issue, go bug them.

https://github.com/microg/GmsCore/issues/1373

**Comment by NotesOfReality** [comment]
> In Youtube Vanced, the account added is not shown in manage account.

I was about to open an issue for this since my second account has been correctly added to Vanced MicroG according to the android settings app, but both Youtube Vanced and Youtube Music Vanced don't list it.

Poco X3 NFC(surya) here with root-less Android 10 QKQ1.200512.002 with the 2020-11-01 Android security patch, MIUI Global 12.0.7 Stable; Vanced Manager 2.5.0, YTV 16.02.35 and YTV Music 4.11.50 and Vanced MicroG 0.2.16.204713.

**Comment by gghhkm** [comment]
> > In Youtube Vanced, the account added is not shown in manage account.
> 
> I was about to open an issue for this since my second account has been correctly added to Vanced MicroG according to the android settings app, but both Youtube Vanced and Youtube Music Vanced don't list it.
> 
> Poco X3 NFC(surya) here with root-less Android 10 QKQ1.200512.002 with the 2020-11-01 Android security patch, MIUI Global 12.0.7 Stable; Vanced Manager 2.5.0, YTV 16.02.35 and YTV Music 4.11.50 and Vanced MicroG 0.2.16.204713.

Again, this is an upstream issue, the only work around is to downgrade to Vanced V15.40.37 & Music V4.04.52.
