### ISSUE TITLE
Bug in microG

### ISSUE THREAD

**Issue by ganeshghutugade** [YTVanced/VancedMicroG#95]
![Screenshot_2021-02-12-07-52-12-85](https://user-images.githubusercontent.com/53371927/107842626-c9c77900-6dea-11eb-96b7-330c8efdba35.jpg)

See screenshot ;

**Comment by PaulCanseco** [comment]
También me sale eso🤧

**Comment by gghhkm** [comment]
You didn't even read it, did you?  😐
