### ISSUE TITLE
I can't sign in it says "Sorry...There was a problem communicating with Google servers.Try again later"

### ISSUE THREAD

**Issue by LS771** [YTVanced/VancedMicroG#96]
![Screenshot_2021-02-15-00-43-36-54](https://user-images.githubusercontent.com/79064234/107891651-b15d7880-6f28-11eb-89bf-04681f23eb49.jpg)

**Comment by gghhkm** [comment]
[VancedLoadingFix](https://github.com/Vendicated/Vanced/blob/master/Guides/VancedLoadingFix.md)
Pls note switching accounts doesn't work on V16.
