### ISSUE TITLE
MicroG conection error

### ISSUE THREAD

**Issue by picsafust** [YTVanced/VancedMicroG#98]
The whole problem started 2 days ago. I had the latest versions installed so I received the error that I do not have an internet connection. I uninstalled the application. Today I put it in the go but microG makes problems. It logs in as a google account, but does not appear in accounts. If I want to log in again, it tells me that the account already exists, but neither the advanced youtube nor the microg is connected. I tried to uninstall chrome, I read that it worked for a while. not me. I uninstalled the application, I reinstalled without success. I downloaded the vanced guide but I couldn't find a solution. I have a oneplus 6t with android 10.3.8
![Screenshot_20210222-075849](https://user-images.githubusercontent.com/79438931/108670342-6246b300-74e7-11eb-8c0a-c9663fc84f8b.jpg)
![Screenshot_20210222-063356](https://user-images.githubusercontent.com/79438931/108670344-62df4980-74e7-11eb-89a1-355e29be6c1b.jpg)
![Screenshot_20210222-063346](https://user-images.githubusercontent.com/79438931/108670346-6377e000-74e7-11eb-8caf-c236f164b063.jpg)

**Comment by gghhkm** [comment]
The manager would have already told you [how to fix it](https://github.com/Vendicated/Vanced/blob/master/Guides/VancedLoadingFix.md) if
1. Vanced Manager is up to date (and you should always update the manager)
2.  Payed any attention to the warning.

**Comment by picsafust** [comment]
> The manager would have already told you [how to fix it](https://github.com/Vendicated/Vanced/blob/master/Guides/VancedLoadingFix.md) if
> 
> 1. Vanced Manager is up to date (and you should always update the manager)
> 2. Payed any attention to the warning.

Thx. That was the first thing I did before I wrote the message. I made the latest updates. and yet it doesn't work. I will try another program.

**Comment by gghhkm** [comment]
> > The manager would have already told you [how to fix it](https://github.com/Vendicated/Vanced/blob/master/Guides/VancedLoadingFix.md) if
> > 
> > 1. Vanced Manager is up to date (and you should always update the manager)
> > 2. Payed any attention to the warning.
> 
> Thx. That was the first thing I did before I wrote the message. I made the latest updates. and yet it doesn't work. I will try another program.

Click the blue text.

**Comment by picsafust** [comment]
OK. it seems we don't get along. I followed all the steps (from how to fix it). for no reason. I will reinstall an older version to see if it works. thank you for your help and time. best regard robert.
