### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mehmetqe** [YTVanced/VancedMicroG#99]
Vanced and microg not working at new android 11 version. I can't add a google account. Please update or help. 
![Screenshot_20210223-134918_Vanced microG](https://user-images.githubusercontent.com/79513872/108833692-3e19cd80-75de-11eb-95e1-05eb14e3c994.jpg)
![Screenshot_20210223-134854](https://user-images.githubusercontent.com/79513872/108833702-4245eb00-75de-11eb-9e5a-72fecd0454ef.jpg)

**Comment by gghhkm** [comment]
https://github.com/YTVanced/Vanced/issues/396
